// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOb7KJqJV230vR9N45D9ihNKSCCHjDsfE',
    appId: '1:550058273174:web:46a4a6bfd32d453f6d95b7',
    messagingSenderId: '550058273174',
    projectId: 'loginexo-8724e',
    authDomain: 'loginexo-8724e.firebaseapp.com',
    databaseURL: 'https://loginexo-8724e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginexo-8724e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlYc2nFHUs4Q_iWKxYLeSh_UlkiNEM_g',
    appId: '1:550058273174:android:9ac474187c7d59836d95b7',
    messagingSenderId: '550058273174',
    projectId: 'loginexo-8724e',
    databaseURL: 'https://loginexo-8724e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginexo-8724e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC81YXLE8pffGPYpGTqujL0ZkXdbxRzY0',
    appId: '1:550058273174:ios:c0fa7d68ecae1c186d95b7',
    messagingSenderId: '550058273174',
    projectId: 'loginexo-8724e',
    databaseURL: 'https://loginexo-8724e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginexo-8724e.appspot.com',
    iosClientId: '550058273174-qco7gtpf82biukk0s89f13lar2qmnj04.apps.googleusercontent.com',
    iosBundleId: 'com.example.connection',
  );
}
